% will be used to display information about how to Tag

function Information (object_handle, event) 
h = msgbox({'The program has generated two tags automatically for you' '' ...
    'If you want to change the positions of these tags you have several options' '' ...
    'To change the viewing window, input the viewing parameters you want (in seconds) and press adjust'...
    '' 'You can manually change the tag positions by clicking the Tag 1 or Tag 2 button and clicking directly on the audio graph where you want the tag to be' ...
    '' 'Once you are happy with the position of the tags, press Accept' '' ...
    'To go to the next phrase, click Next Phrase'}, 'How to Tag');
end